FROM golang:1.24 AS build

WORKDIR /app

COPY go.mod ./
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /collector ./cmd/collector

FROM gcr.io/distroless/base-debian12

COPY --from=build /collector /collector

EXPOSE 50051

ENTRYPOINT ["/collector"]
