FROM golang:1.24 AS build

WORKDIR /app

COPY go.mod ./
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /api-gateway ./cmd/api-gateway

FROM gcr.io/distroless/base-debian12

COPY --from=build /api-gateway /api-gateway

EXPOSE 8080

ENTRYPOINT ["/api-gateway"]
